### ISSUE TITLE
Determine which APIs we can access

### ISSUE THREAD

**Issue by nwrighteous** [nuvention-web/Team-D#11]
**What APIs for video data can we access? What platforms are most important for MVP?**

- YouTube
- Facebook
- Instagram
- Vimeo
- Snapchat
- Facebook Live
- Periscope

**Enhancements**:

- Use JSON Placeholder: this will give us fake data to feed the beast for testing in case we need more.

**Test criteria**:
- We have real-time (or as close to it), dynamic data to work with.

**Comment by nwrighteous** [comment]
Which APIs can get we get to build an MVP?
- YouTube
- Facebook
- Instagram
- Vimeo
- JSON Placeholder

**Comment by megancon** [comment]
APIs accessed and integrated: 
- Facebook

APIs in progress:
- YouTube 
----> Data API works
-----> Analytics API issue!!
 http://stackoverflow.com/questions/43269296/i-cannot-enable-youtube-analytics-api-at-google-developers-console

- Twitter
----> only available commercially through Gnip, but might not be necessary since not used by our current beta testers

- Ooyala (on-site video)
---->  Waiting for data/info in follow up interview w/ Amanda Yang (local beta tester)
